namespace UCR.ECCI.PI.ThemePark.Backend.Domain.Entities.AccountManagement;

/// <summary>
/// Represents an audit record for user actions in the system.
/// </summary>
public class UserAudit
{
    /// <summary>
    /// Gets or sets the unique identifier for the user audit record.
    /// Automatically generated by the database.
    /// </summary>
    public int AuditId { get; set; }
    /// <summary>
    /// Gets or sets the username of the user being audited.
    /// </summary>
    public string UserName { get; set; } = null!;
    /// <summary>
    /// Gets or sets the first name of the user being audited.
    /// </summary>
    public string FirstName { get; set; } = null!;
    /// <summary>
    /// Gets or sets the last name of the user being audited.
    /// </summary>
    public string LastName { get; set; } = null!;
    /// <summary>
    /// Gets or sets the email address of the user being audited.
    /// </summary>
    public string Email { get; set; } = null!;
    /// <summary>
    /// Gets or sets the phone number of the user being audited.
    /// </summary>
    public string Phone { get; set; } = null!;
    /// <summary>
    /// Gets or sets the identity number of the user being audited.
    /// </summary>
    public string IdentityNumber { get; set; } = null!;
    /// <summary>
    /// Gets or sets the birth date of the user being audited.
    /// </summary>
    public DateTime BirthDate { get; set; }
    /// <summary>
    /// Gets or sets the date and time when the audit record was last modified.
    /// </summary>
    public DateTime ModifiedAt { get; set; }
    /// <summary>
    /// Gets or sets the action performed on the user that is being audited.
    /// </summary>
    public string Action { get; set; } = null!;
}
